# Generated by Django 2.1.5 on 2019-01-30 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='categoria',
            field=models.CharField(choices=[('gastos', 'Gastos'), ('diversion', 'Diversión'), ('ahorro', 'Ahorro')], default='gastos', max_length=255, verbose_name='Categoría'),
        ),
    ]
