# Generated by Django 2.1.5 on 2019-01-31 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0002_movimiento_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='subcategoria',
            field=models.CharField(choices=[('', ''), ('', ''), ('', '')], default='gastos', max_length=255, verbose_name='Categoría'),
        ),
    ]
